module.exports = [
    {
        item_name: "Income",
        amount: 1300,
        date: "2022-07-01",
        from: "Employer",
        category: "Income",
    },
    {
        item_name: "Pet Food",
        amount: -150,
        date: "2022-07-04",
        from: "Pet Store",
        category: "pets",
    },
    {
        item_name: "Savings",
        amount: -300,
        date: "2022-07-11",
        from: "Bank",
        category: "Savings",
    },
    {
        item_name: "Groceries",
        amount: -250,
        date: "2022-07-12",
        from: "Grocery Store",
        category: "Food",
    },
    {
        item_name: "Starbucks",
        amount: -10,
        date: "2022-07-12",
        from: "Starbucks",
        category: "Food",
    },
    {
        item_name: "Income",
        amount: 1300,
        date: "2022-07-15",
        from: "Employer",
        category: "Income",
    },
    {
        item_name: "Rent",
        amount: -1500,
        date: "2022-07-18",
        from: "Apartment Management",
        category: "Rent",
    },
    {
        item_name: "Starbucks",
        amount: -5,
        date: "2022-07-20",
        from: "Starbucks",
        category: "Food",
    },
    {
        item_name: "Chipotle",
        amount: -20,
        date: "2022-07-23",
        from: "Chipotle",
        category: "Food",
    },
    {
        item_name: "Income",
        amount: 1300,
        date: "2022-07-29",
        from: "Employer",
        category: "Income",
    },
];