module.exports = [
    {
        item_name: "income",
        amount: 1300,
        date: "July 1, 2022",
        from: "employer",
        category: "income",
    },
    {
        item_name: "pet food",
        amount: 150,
        date: "July 4, 2022",
        from: "pet store",
        category: "pets",
    },
    {
        item_name: "savings",
        amount: 300,
        date: "July 11, 2022",
        from: "bank",
        category: "savings",
    },
    {
        item_name: "groceries",
        amount: 250,
        date: "July 12, 2022",
        from: "grocery store",
        category: "food",
    },
    {
        item_name: "starbucks",
        amount: 10,
        date: "July 12, 2022",
        from: "starbucks",
        category: "food",
    },
    {
        item_name: "income",
        amount: 1300,
        date: "July 15, 2022",
        from: "employer",
        category: "income",
    },
    {
        item_name: "rent",
        amount: 1500,
        date: "July 18, 2022",
        from: "apartment management",
        category: "rent",
    },
    {
        item_name: "starbucks",
        amount: 5,
        date: "July 20, 2022",
        from: "starbucks",
        category: "food",
    },
    {
        item_name: "chipotle",
        amount: 20,
        date: "July 23, 2022",
        from: "chipotle",
        category: "food",
    },
    {
        item_name: "income",
        amount: 1300,
        date: "July 29, 2022",
        from: "employer",
        category: "income",
    },
];